name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files (Debug)
        run: ls -la

      - name: Deploy files to Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: "184.168.123.93"
          username: "adminhala"
          password: vjs9cdt%rVuf91q0
          source: "*"
          target: "/var/www/my-new-app/"
